  - name: Instalar nfs-utils.
    package:
      name: 
       - nfs-utils
      state: latest

  - name: Instalar net-tools.
    package:
      name: 
       - net-tools
      state: latest

  - name: Verificar ejecución de nfs-server.
    systemd: 
      name: nfs-server
      daemon_reload: yes
      enabled: yes

  
  - name: Configurar el acceso al share de NFS.
    lineinfile:
      path: /etc/exports
      line: /mnt/resource	{{ item }}(rw,sync)
    with_items:
      - "{{ groups['worker'] }}"
      - "{{ groups['master'] }}"

  - name: Aplicar nueva configuración al /etc/exports
    shell: exportfs -r
  
  - shell: exportfs -s
    register: export_result

  - name: debug de exports
    debug: msg="{{ export_result.stdout_lines }}"

  - name: Configuracion firwall servicio nfs
    firewalld:
      service: nfs
      permanent: true
      state: enabled

  - name: Configuracion firwall servicio rpc-bind
    firewalld:
      service: rpc-bind
      permanent: true
      state: enabled

  - name: Configuracion firwall servicio mountd
    firewalld:
      service: mountd
      permanent: true
      state: enabled
