- name: activar transparent masquerading
  modprobe:
    name: br_netfilter
    state: present

- name: Configuracion firwall
  firewalld:
    masquerade: yes
    state: enabled
    permanent: true

- name: Permitir que kubernetes maneje correctamente el tráfico con el cortafuegos. (1)
  shell: | 
          cat <<EOF > /etc/sysctl.d/k8s.conf 
          net.bridge.bridge-nf-call-ip6tables = 1 
          net.bridge.bridge-nf-call-iptables = 1 
          EOF

- name: Permitir que kubernetes maneje correctamente el tráfico con el cortafuegos. (2)
  shell: "sysctl --system"

- name: install docker repository
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    warn: false

- name: install docker version 19.03
  command: dnf install docker-ce-19.03.14-3.el8 containerd.io -y
  args:
    warn: false

- name: Verificar ejecución de docker.
  systemd: 
    name: docker
    daemon_reload: yes
    enabled: yes