  - name: Instalar Chrony.
    package:
      name: 
       - chrony
      state: latest

  - name: Verificar ejecución de Chrony.
    systemd: 
      name: chronyd
      daemon_reload: yes
      enabled: yes