- name: activar transparent masquerading
  modprobe:
    name: br_netfilter
    state: present

- name: Configuracion firwall
  firewalld:
    masquerade: yes
    state: enabled
    permanent: yes

- name: Iniciamos firewalld
  shell: "service firewalld start"


- name: Permitir que kubernetes maneje correctamente el tr치fico con el cortafuegos. (1)
  shell: | 
          cat <<EOF > /etc/sysctl.d/k8s.conf 
          net.bridge.bridge-nf-call-ip6tables = 1 
          net.bridge.bridge-nf-call-iptables = 1 
          EOF

- name: Permitir que kubernetes maneje correctamente el tr치fico con el cortafuegos. (2)
  shell: "sysctl --system"

- name: install docker repository
  command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    warn: false

- name: install docker version 19.03
  command: dnf install docker-ce-19.03.14-3.el8 containerd.io -y
  args:
    warn: false

- name: Iniciamos docker
  shell: "service docker start"

- name: Verificar ejecuci칩n de docker.
  systemd: 
    name: docker
    daemon_reload: yes
    enabled: yes

- name: Configuramos el repositorio de kubernetes
  shell: | 
          cat <<EOF > /etc/yum.repos.d/kubernetes.repo 
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          exclude=kubelet kubeadm kubectl
          EOF

- name: Comprobamos si ya esta instaldo kubelet
  package_facts:
    manager: "auto"

- name: Instalamos - kubelet kubeadm kubectl
  when: "not 'kubelet' in ansible_facts.packages"
  yum:
    name: "{{ packages }}"
    state: latest
    disable_excludes: all
    exclude: kubernetes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Verificar ejecuci칩n de kubernetes.
  systemd: 
    name: kubelet
    daemon_reload: yes
    enabled: yes