- name: Despliegues comunes para todos los nodos
  hosts: all
  become: yes
  gather_facts: true
  roles:
    - comunes

- name: Despliegues nodo master
  hosts: master
  vars_files:
    - "group_vars/comunes.yaml"
  become: yes
  gather_facts: true
  roles:
    - master

- name: Despliegues nodo nfs
  hosts: nfs
  become: yes
  gather_facts: true
  roles:
    - nfs

- name: Despliegues nodo worker
  hosts: worker
  vars_files:
    - "group_vars/comunes.yaml"
  become: yes
  gather_facts: true
    - worker
 