  - name: Configuracion firwall servicio mountd
    firewalld:
      port: 10250/tcp
      permanent: true
      state: enabled
      immediate: yes
      zone: public

  - firewalld:
      port: 30000-32767/tcp
      permanent: true
      state: enabled
      immediate: yes
      zone: public
  
  - name: Copiamos el token en el worker node
    copy: src={{ token_file }} dest=join_token

  - name: Enlazamos el worker node en el cluster 
    shell: |
     cat join_token | tail -2 > out.sh
     sh out.sh
    register: kubeadm_join_cmd   

  - name: debug
    debug: msg="{{ kubeadm_join_cmd.stdout }}"
    delegate_to: 127.0.0.1